export const FETCH_ACCOUNT_INFO: 'account/FETCH_ACCOUNT_INFO' =
  'account/FETCH_ACCOUNT_INFO';
export const POPULATE_ACCOUNT_INFO: 'account/POPULATE_ACCOUNT_INFO' =
  'account/POPULATE_ACCOUNT_INFO';
export const FETCHING_ACCOUNT_INFO: 'account/FETCHING_ACCOUNT_INFO' =
  'account/FETCHING_ACCOUNT_INFO';
